"use client";
import { useState } from "react";
import Parallax from "./parallax";
import EmailNotify from "./email-notify";
const wines = [
 {name:"台灣威士忌",en:"TAIWAN WHISKY",type:"蒸餾酒",place:"宜蘭 · 島嶼熟成",mark:"山",color:"amber",notes:"熱帶果香 / 香草 / 橡木",story:"溫暖潮濕的島嶼氣候，賦予威士忌鮮明的熟成個性。從果香到木質尾韻，探索台灣風土的豐富層次。"},
 {name:"金門高粱",en:"KAOLIANG SPIRIT",type:"蒸餾酒",place:"金門 · 淬鍊清香",mark:"金",color:"clear",notes:"穀物香 / 清香 / 悠長尾韻",story:"以高粱釀出率真而深刻的性格。清香、穀物氣息與俐落口感，承載離島的日常與宴席記憶。"},
 {name:"台灣梅酒",en:"TAIWAN PLUM WINE",type:"果實酒",place:"南投 · 青梅時節",mark:"梅",color:"plum",notes:"青梅 / 果酸 / 柔和甘甜",story:"把青梅的清新收藏進酒裡，讓酸與甜緩緩交織。冰飲或搭配氣泡水，都能開啟輕盈的品飲時光。"},
 {name:"在地精釀",en:"CRAFT BEER",type:"釀造酒",place:"台灣 · 自由釀造",mark:"釀",color:"beer",notes:"麥芽 / 酒花 / 在地靈感",story:"從麥芽與酒花出發，探索茶、果實等在地元素的可能。每一款釀造，都是對這座島嶼的新提案。"}
];
function Bottle({mark="山",color="amber"}:{mark?:string;color?:string}){return <div className={`bottle ${color}`} aria-hidden="true"><div className="cap"/><div className="neck"/><div className="bottle-body"><div className="label"><small>ISLE & SPIRIT</small><b>{mark}</b><i>FORMOSA COLLECTION</i><hr/><small>CRAFTED IN TAIWAN</small></div><span className="bottle-foot">福爾摩沙・風土之作</span></div></div>}
export default function Home(){const [filter,setFilter]=useState("全部酒款");return <div className="site"><Parallax />
<header><a className="brand" href="#"><b>島</b><span>島嶼之釀<small>ISLE & SPIRIT</small></span></a><nav aria-label="主要導覽"><a href="#collection">探索酒款</a><a href="#story">風土故事</a><a href="/blog">風味誌</a><a className="game-nav" href="/game">丟瓶樂</a><a href="#about">關於我們</a></nav><a className="nav-button" href="#collection">開啟品味旅程 <span>↗</span></a></header>
<main><section className="hero"><div className="hero-copy"><div className="eyebrow">● &nbsp; THE SPIRIT OF TAIWAN</div><h1>一座島嶼，<br/>千般<span>風味。</span></h1><p>從山林的溫潤，到海風的醇厚。<br/>品味台灣特色酒釀，讓每一口，<br className="mobile-break"/>都成為認識這片土地的開始。</p><div className="actions"><a className="primary" href="#collection">探索島嶼酒藏 <span>↗</span></a><a className="story-link" href="#story"><span>▷</span> 閱讀風土故事</a></div><div className="coordinates">25° N · 121° E <i/> 在地風土，釀出不凡。</div></div><div className="hero-art"><div className="glow"/><div className="orbit"/><div className="orbit second"/><span className="giant">醇</span><div className="pedestal"/><div className="hero-bottle"><Bottle/></div><div className="floating glass"><span>✧</span><div>島嶼風土・細緻入藏<small>A TASTE OF OUR ISLAND</small></div></div><div className="art-caption">01 / FORMOSA COLLECTION</div></div></section>
<div className="values"><small>ROOTED IN TAIWAN</small><p>在地原料 <span>✧</span> 匠心釀造 <span>✧</span> 島嶼風味 <span>✧</span> 慢飲生活</p><small>用一杯，認識台灣。</small></div>
<section id="collection" className="collection"><div className="section-top"><div><div className="eyebrow">THE COLLECTION</div><h2>島嶼精選，各有風格。</h2></div><p>從經典烈酒到清新果釀<br/>找到與你此刻心情相映的風味。</p></div><div className="filters" aria-label="酒類篩選">{["全部酒款","蒸餾酒","果實酒","釀造酒"].map(f=><button key={f} onClick={()=>setFilter(f)} aria-pressed={filter===f} className={filter===f?"active":""}>{f}{f==="全部酒款"&&<small>04</small>}</button>)}</div><div className="cards">{wines.filter(w=>filter==="全部酒款"||filter===w.type).map(w=><article className="card glass" key={w.name}><div className={`card-art ${w.color}`}><span className="badge">{w.type}</span><span className="watermark">{w.mark}</span><Bottle mark={w.mark} color={w.color}/></div><div className="card-copy"><div className="origin">{w.place}</div><h3>{w.name}</h3><div className="english">{w.en}</div><div className="card-bottom"><span>{w.notes}</span><button aria-label={`認識${w.name}`} onClick={()=>{(document.getElementById(`wine-${w.color}`) as HTMLDialogElement).showModal();}}>↗</button></div></div><dialog id={`wine-${w.color}`} onClick={e=>{if(e.target===e.currentTarget)e.currentTarget.close()}}><div className="dialog-content"><form method="dialog"><button className="close" aria-label="關閉介紹">✕</button></form><div className="eyebrow">{w.en}</div><h2>{w.name}</h2><div className="origin">{w.place}</div><p>{w.story}</p><div className="notes">風味筆記<span>{w.notes}</span></div><small>各酒廠與酒款風味有所不同，以上為概括介紹。</small></div></dialog></article>)}</div><p className="disclaimer">以酒類風格為靈感的概念酒藏 · 瓶身為示意設計</p></section>
<section id="story" className="story glass"><div className="landscape" aria-hidden="true"><div className="sun"/><div className="mountain"/><div className="mountain front"/><span>山海之間<br/>風味成形</span><small>TAIWAN · OUR TERROIR</small></div><div className="story-copy"><div className="eyebrow">BORN OF THIS LAND</div><h2>好風味，<br/>有自己的來處。</h2><p>山脈、海洋、季風與時間，寫下台灣獨有的風土。釀酒人以穀物與果實為語言，將土地的性格，化成杯中的細節。</p><p>我們相信，認識一款酒，也是在認識一個地方。放慢腳步，從香氣開始，聽見島嶼的故事。</p><a href="#about">認識島嶼之釀 <span>↗</span></a></div></section>
<section id="about" className="about"><div className="eyebrow">SIP SLOWLY. DISCOVER MORE.</div><h2>把日子放慢，把台灣細品。</h2><p>島嶼之釀是一份獻給台灣風味的選集。<br/>從一杯酒的香氣出發，收藏土地、人與時間的故事。</p><a className="primary" href="#collection">找到你的島嶼風味 <span>↗</span></a></section><EmailNotify /></main>
<footer><a className="brand" href="#"><b>島</b><span>島嶼之釀<small>ISLE & SPIRIT</small></span></a><span>© 2026 ISLE & SPIRIT. 台灣風味概念網站</span><a href="#">回到頂端 ↑</a></footer><div className="responsible">禁止酒駕 <span>·</span> 未滿十八歲禁止飲酒 <span>·</span> 理性品飲，享受生活</div></div>}

